### PR TITLE
add persistDefaultValue and npm audit fix

### PR DESCRIPTION
**Pull request by iandvt**
This change enables users to update/persist the default data as it changes over time. Currently the only way to achieve this is manually deleting the item from the S3 bucket.

### CODE REVIEW

**Comment by iandvt** [comment]
@nicekiwi || @pharindoko - Could you let me know if this PR is sufficient or requires any changes?

**Comment by pharindoko** [comment]
@iandvt  hmm I checked your code but don`t get the point.
All I see here is that you refactored the code piece into a new function...
https://github.com/nicekiwi/lowdb-adapter-aws-s3/blob/666b4129fdd349e5f90063ce43cc8a2d68f79aa4/src/main.js#L64

**Comment by pharindoko** [comment]
@nicekiwi do you still maintain this repository ?

**Comment by iandvt** [comment]
> @iandvt hmm I checked your code but don`t get the point.
> All I see here is that you refactored the code piece into a new function...
> https://github.com/nicekiwi/lowdb-adapter-aws-s3/blob/666b4129fdd349e5f90063ce43cc8a2d68f79aa4/src/main.js#L64

@pharindoko - This PR enables users to override the data that resides in S3.

**Comment by nicekiwi** [comment]
> > @iandvt hmm I checked your code but don`t get the point.
> > All I see here is that you refactored the code piece into a new function...
> > https://github.com/nicekiwi/lowdb-adapter-aws-s3/blob/666b4129fdd349e5f90063ce43cc8a2d68f79aa4/src/main.js#L64
> 
> @pharindoko - This PR enables users to override the data that resides in S3.

How does it do that though? The plugin itself updates data in S3, this just seems to break that into a new function with no added feature or benefit.

**Comment by iandvt** [comment]
@nicekiwi - It will enable me to call `await persistDefaultValue` before my server starts which will override the data inside of S3.

**Comment by iandvt** [comment]
@nicekiwi  && @pharindoko - Would you like me to remove node@4 from Travis with this PR? I believe it would allow you to close out #4.

**Comment by iandvt** [comment]
> @nicekiwi && @pharindoko - Would you like me to remove node@4 from Travis with this PR? I believe it would allow you to close out #4.

@pharindoko - PR updated

**Comment by pharindoko** [comment]
I fully understand now what you want to achieve but the main issue here is that lowdb itself does not support such a method. 
there are only these methods:
read, write, setstate, getstate
 

The question that comes up in my mind. Why you don't write yourself a module that supports your specific method ? 

And another thing - would it not be the same (persistdefaultvalue) as the setstate method lowdb already provides ?

**Pull request closed without merging**
